version: 0.0
os: linux
files:
  - source: /app.js
    destination: nodeapp/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
  ApplicationStart:
    - location: scripts/restart_server
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300

